sudo: required
services:
  - docker

before_install:
  - docker build -t aleksijaakkojuhani/nextjs-test -f ./client/Dockerfile.dev ./client

script:
  - docker run aleksijaakkojuhani/nextjs-test npm run test
