version: '3'
services:
  nginx:
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
  #tests:
   # build:
    #  dockerfile: Dockerfile.dev
     # context: ./client
    #volumes:
     # - /app/node_modules
     # - .:/app
    #command: ["npm", "run", "test"]